- name: Install dependencies
  ansible.builtin.package:
    name:
      - php8.4-fpm
      - php8.4-mysql
      - composer
      - nginx
    state: present

- name: Create system user
  ansible.builtin.user:
    name: "{{ pve_importer_unix_user }}"
    group: "{{ pve_importer_unix_user }}"
    system: true

- name: Create application directory
  ansible.builtin.file:
    path: "{{ pve_importer_install_path }}"
    owner: "{{ pve_importer_unix_user }}"
    group: "{{ pve_importer_unix_user }}"
    mode: "0700"

- name: Clone PVE-Importer Git repository
  ansible.builtin.git:
    repo: "{{ pve_importer_git_url }}"
    version: "{{ pve_importer_git_branch }}"
    dest: "{{ pve_importer_install_path }}"

- name: Ensure upload directory exists
  ansible.builtin.file:
    path: "{{ pve_importer_upload_dir }}"
    state: directory
    owner: "{{ pve_importer_unix_user }}"
    group: "{{ pve_importer_unix_user }}"
    mode: "0700"

- name: Install .env.local
  ansible.builtin.template:
    src: env.local.j2
    dest: "{{ pve_importer_install_path }}/.env.local"
    owner: "{{ pve_importer_unix_user }}"
    group: "{{ pve_importer_unix_user }}"
    mode: "0600"

- name: Install composer dependencies
  ansible.builtin.command:
    chdir: "{{ pve_importer_install_path }}"
    cmd: composer install --no-dev --optimize-autoloader
  become: true
  become_user: "{{ pve_importer_unix_user }}"
  register: pve_importer_composer_install_result
  changed_when: pve_importer_composer_install_result.rc != 0

- name: Install PHP-FPM pool configuration
  ansible.builtin.template:
    src: pve_importer.php-pool.j2
    dest: /etc/php/8.4/fpm/pool.d/pve_importer.conf
    mode: "0640"

- name: Enable PHP-FPM
  ansible.builtin.service:
    name: php8.4-fpm
    enabled: true
    state: restarted

- name: Install nginx configuration
  ansible.builtin.template:
    src: pve_importer.nginx.j2
    dest: /etc/nginx/sites-available/pve_importer
    mode: "0640"

- name: Enable nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/pve_importer
    state: link
    src: /etc/nginx/sites-available/pve_importer

- name: Enable nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: restarted
