pve_importer_install_path: /opt/pve-importer
pve_importer_git_url: https://github.com/rloewenross/pve-importer.git
pve_importer_git_branch: main
pve_importer_proxmox_storage: local
pve_importer_upload_dir: /opt/pve-importer/var/uploads
pve_importer_database_user: pve_importer
pve_importer_database_name: pve_importer
pve_importer_web_url: import.example.com
pve_importer_unix_user: pve_importer
pve_importer_php_socket: /var/run/php/pve_importer.sock
pve_importer_https_cert_dest_path: /etc/ssl/pve-importer/cert.pem
pve_importer_https_key_dest_path: /etc/ssl/pve-importer/key.pem
pve_importer_php_fpm_pm: dynamic
pve_importer_php_fpm_pm_max_children: 10
pve_importer_php_fpm_pm_start_servers: 4
pve_importer_php_fpm_pm_min_spare_servers: 2
pve_importer_php_fpm_pm_max_spare_servers: 6
pve_importer_php_fpm_pm_max_spawn_rate: 4
pve_importer_php_fpm_pm_process_idle_timeout: 10s
pve_importer_php_fpm_pm_max_requests: 0
